### PR TITLE
Bugfixes

### LINKED ISSUE #6: java.lang.NoSuchFieldError: POLAR_BEAR
Spigot 1.8.8
Genie 1.2.0

```
[09:54:34 ERROR]: Could not pass event EntityDeathEvent to Genie v1.2.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:874) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntitySkeleton.die(EntitySkeleton.java:142) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityWolf.r(EntityWolf.java:218) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityWolf.m(EntityWolf.java:136) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.EntityWolf.t_(EntityWolf.java:151) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchFieldError: POLAR_BEAR
        at com.djrapitops.genie.listeners.DeathListener.onDeath(DeathListener.java:42) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 29 more
```

### LINKED ISSUE #8: Mobs don't Stack on 1.8.X

### PR DESCRIPTION
**Pull request by Sharpjaws**
Closes #8 and closes #6 

non-hostile mobs types are now added to a enum that will be used to compare the Entities. Since it compares them by name it prevents NoSuchField errors from happening between old and new minecraft versions. Ofcourse the polar bear entity is not available in 1.8 resulting in that error. My method just gets the name and compares them to the enums which might be a better solution as you can easily add more mobs in the future to the enum if needed.

Also fixed a bug where the lamp item could not be spawned due to method changes between spigot versions affecting 1.8(Needs confirmation) - 1.8.8(Tested) including the setunbreakable()  function being changed slightly.

### CODE REVIEW

**Review by AuroraLS3 — CHANGES_REQUESTED** [review]
First of all, huge thank you for fixing these bugs.
I've been coding Plan so there has been little time to look into these issues.

There is a simpler solution for the entity problem (In use elsewhere, forgot it in the DeathListener) - As seen here:
https://github.com/Rsl1122/Genie/blob/master/Genie/src/main/java/com/djrapitops/genie/wishes/WishManager.java#L166

**Comment by Sharpjaws** [comment]
I see, no problem I'll change that right away.

**Comment by Sharpjaws** [comment]
Alright so for confirmation do you want that non-hostile mobs are able to drops the lamp but not the ones you specified in the prevented mobs list? Or do you want to prevent the non-hostile mobs aswell?

**Comment by AuroraLS3** [comment]
So that the non-hostile mobs don't drop LAMPS, & hostile mobs drop. 
The prevented entities in that method are not mobs and deathlistener can't give those as entities. 
So a list of non hostile mob enum names as strings for that EnumUtility method similar to the linked method.

**Comment by Sharpjaws** [comment]
Got it, Adjusted. Should be done by now unless there are more changes needed

**Pull request merged**
